//! Smoke test for **multi-provide** — one provider struct hosting two
//! `#[toolkit::provides]` invocations for two distinct contracts.
//!
//! Validates that:
//! - Two `#[toolkit::provides]` on the same struct produce two distinct
//!   `wire_<contract>` methods.
//! - Both methods can be invoked from a single `init`, registering both
//!   trait objects in the shared `ClientHub`.
//! - `ClientHub::get::<dyn TraitA>()` and `get::<dyn TraitB>()` resolve to
//!   the right adapters.

#![allow(clippy::unwrap_used)]
#![cfg_attr(coverage_nightly, coverage(off))]

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use tokio_util::sync::CancellationToken;
use toolkit::config::ConfigProvider;
use toolkit::{ClientHub, GearCtx};
use toolkit_canonical_errors::CanonicalError;
use toolkit_contract::policy::PolicyStack;
use toolkit_security::SecurityContext;
use uuid::Uuid;

// ----- Contract A ------------------------------------------------------

#[toolkit::contract(gear = "multi-provide-smoke", version = "v1")]
pub trait FooApi: Send + Sync {
    async fn ping(&self, ctx: SecurityContext) -> Result<u32, CanonicalError>;
}

struct FooLocal;
#[async_trait]
impl FooApi for FooLocal {
    async fn ping(&self, _ctx: SecurityContext) -> Result<u32, CanonicalError> {
        Ok(42)
    }
}

// ----- Contract B ------------------------------------------------------

#[toolkit::contract(gear = "multi-provide-smoke", version = "v1")]
pub trait BarApi: Send + Sync {
    async fn pong(&self, ctx: SecurityContext) -> Result<String, CanonicalError>;
}

struct BarLocal;
#[async_trait]
impl BarApi for BarLocal {
    async fn pong(&self, _ctx: SecurityContext) -> Result<String, CanonicalError> {
        Ok("pong".to_owned())
    }
}

// ----- Provider that auto-wires both ----------------------------------

/// Test-only provider; the `#[toolkit::gear]` attribute is **not** applied
/// because we don't want gear registry side-effects in unit tests — only
/// the inherent methods generated by `#[toolkit::provides]` matter here.
#[toolkit::provides(
    contract   = self::FooApi,
    local      = MultiProvider::build_foo,
    transports = [local],
)]
#[toolkit::provides(
    contract   = self::BarApi,
    local      = MultiProvider::build_bar,
    transports = [local],
)]
#[derive(Default)]
pub struct MultiProvider;

impl MultiProvider {
    // `#[toolkit::provides]` applies `?` to the `local` factory's return
    // value, so `Result` is a required part of the macro's calling
    // convention, not incidental — these always succeed.
    #[allow(clippy::unnecessary_wraps)]
    fn build_foo(_ctx: &GearCtx, _policies: Arc<PolicyStack>) -> anyhow::Result<Arc<dyn FooApi>> {
        Ok(Arc::new(FooLocal))
    }

    #[allow(clippy::unnecessary_wraps)]
    fn build_bar(_ctx: &GearCtx, _policies: Arc<PolicyStack>) -> anyhow::Result<Arc<dyn BarApi>> {
        Ok(Arc::new(BarLocal))
    }
}

// ----- Harness --------------------------------------------------------

struct StaticProvider(HashMap<String, serde_json::Value>);

impl ConfigProvider for StaticProvider {
    fn get_gear_config(&self, gear_name: &str) -> Option<&serde_json::Value> {
        self.0.get(gear_name)
    }
}

fn empty_ctx(gear_name: &str) -> GearCtx {
    GearCtx::new(
        gear_name,
        Uuid::nil(),
        Arc::new(StaticProvider(HashMap::new())),
        Arc::new(ClientHub::new()),
        CancellationToken::new(),
    )
}

// ----- Tests ----------------------------------------------------------

#[tokio::test]
async fn both_wire_methods_register_independently() {
    let ctx = empty_ctx("multi-provide-smoke");
    let m = MultiProvider;

    m.wire_foo_api(&ctx).await.unwrap();
    m.wire_bar_api(&ctx).await.unwrap();

    let foo = ctx.client_hub().get::<dyn FooApi>().unwrap();
    let bar = ctx.client_hub().get::<dyn BarApi>().unwrap();

    assert_eq!(foo.ping(SecurityContext::anonymous()).await.unwrap(), 42);
    assert_eq!(
        bar.pong(SecurityContext::anonymous()).await.unwrap(),
        "pong"
    );
}

#[tokio::test]
async fn missing_wiring_falls_back_to_local() {
    // No `client_wiring` in config → both contracts default to Local.
    let ctx = empty_ctx("multi-provide-smoke");
    let m = MultiProvider;

    m.wire_foo_api(&ctx).await.expect("foo wires");
    m.wire_bar_api(&ctx).await.expect("bar wires");

    assert!(ctx.client_hub().get::<dyn FooApi>().is_ok());
    assert!(ctx.client_hub().get::<dyn BarApi>().is_ok());
}
